name: 'CI on Push'

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@v1.0
      with:
        version: 26.3
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: 'Run tests'
      run: |
        ./run-tests.bash
